#! /usr/bin/env python3

import argparse
import contextlib
import datetime
import os
import time
import sys

import base


@contextlib.contextmanager
def pomodoro_lock():
    lock_path = '/tmp/pomodoro'
    if os.path.exists(lock_path):
        raise RuntimeError('Currently locked')
    with open(lock_path, 'w') as f:
        f.write(str(os.getpid()))
    try:
        yield
    finally:
        os.remove(lock_path)


def run_pomodoro_forever():
    pomodoro = base.Pomodoro()


if __name__ == "__main__":
    with pomodoro_lock():
        run_pomodoro_forever()
        print(pomodoro)
        print(pomodoro.state)
    # TODO start/end
    # TODO alignment flag
    #parser = argparse.ArgumentParser(description='Fire up a pomodoro')
    #parser.add_argument(
    #main(sys.argv)
    #main()
